LabG9/Controllers/FacturaController.cs
using LabG9.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabG9.Controllers
{
    public class FacturaController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();

        [Authorize]
        [HttpGet]

        public ActionResult HistorialPedido()
        {
            var clienteId = User.Identity.GetUserId();
            var cliente = context.Users.FirstOrDefault(u => u.Id == clienteId);
            ViewBag.Nombre = cliente.nombreCompleto;

            var Facturas = context.Facturas.Where(c => c.ClienteId == clienteId).ToList();

            return View(Facturas);
        }
        [Authorize]
        [HttpGet]
        public ActionResult DetalleFactura(int id)
        {
            var factura = context.Facturas.FirstOrDefault(f => f.IdFactura == id);


            var detallesFactura = context.DetalleFacturas
                                          .Where(d => d.IdFactura == id)
                                          .Include(d => d.Producto)
                                          .ToList();


            ViewBag.Factura = factura;

            return View(detallesFactura);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Facturas()
        {
            var facturas = context.Facturas.ToList();
            return View(facturas);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Editar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var factura = context.Facturas.Find(id);
            if (factura == null)
                return HttpNotFound();
            return View(factura);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Editar(Factura factura)
        {
            if (ModelState.IsValid)
            {
                context.Entry(factura).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Facturas");
            }
            return View(factura);
        }
    }
}

LabG9/Controllers/ProductoController.cs
using LabG9.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabG9.Controllers
{
    public class ProductoController : Controller
    {

        private ApplicationDbContext context = new ApplicationDbContext();
        [HttpGet]
        public ActionResult Catalogo()
        {
            ViewBag.Categorias = context.Categorias.ToList();
            var productosDisponibles = context.Productos.Where(p => p.Estado == true).ToList();
            return View(productosDisponibles);
        }

        [HttpGet]
        public ActionResult FiltrarXCategoria(int? IdCategoria)
        {
            ViewBag.Categorias = context.Categorias.ToList();

            if (IdCategoria == null)
            {
                ModelState.AddModelError("", "Seleccione una Categoría");
                return RedirectToAction("Catalogo");
            }

            var productosDisponibles = context.Productos.Where(p => p.IdCategoria == IdCategoria && p.Estado == true).ToList();
            return View(productosDisponibles);
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public ActionResult GestionProductos()
        {
            ViewBag.Categorias=context.Categorias.ToList();
            var productos=context.Productos.ToList();
            return View(productos);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Crear()
        {
            ViewBag.Categorias = context.Categorias.ToList();
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Crear(Producto producto)
        {
            ViewBag.Categorias = context.Categorias.ToList();
            if (ModelState.IsValid)
            {
                context.Productos.Add(producto);
                context.SaveChanges();
                return RedirectToAction("GestionProductos");
            }
            return View(producto);

        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Editar(int? id)
        {
            ViewBag.Categorias = context.Categorias.ToList();
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var producto = context.Productos.Find(id);
            if (producto == null)
                return HttpNotFound();
            return View(producto);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Editar(Producto producto)
        {
            ViewBag.Categorias = context.Categorias.ToList();
            if (ModelState.IsValid)
            {
                context.Entry(producto).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("GestionProductos");
            }
            return View(producto);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Eliminar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var producto=context.Productos.SingleOrDefault(r=>r.IdProducto==id);
            if (producto == null)
                return HttpNotFound();
            return View(producto);  
        }
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Eliminar")]
        public ActionResult EliminarConfirmacion(int? id)
        {
            var producto = context.Productos.Find(id);
            context.Productos.Remove(producto);
            context.SaveChanges();
            return RedirectToAction("GestionProductos");

        }


    }
    }

LabG9/Controllers/ReportesController.cs
using LabG9.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabG9.Controllers
{
    public class ReportesController : Controller
    {

        private ApplicationDbContext context = new ApplicationDbContext();
        [Authorize(Roles ="Admin")]
        [HttpGet]
        public ActionResult VentasPorMes()
        {
            var reporte = context.Database.SqlQuery<VentasModelView>(
                "EXEC sp_Reportes_VentasPorMes"
            ).ToList();

            return View(reporte);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult ProductosMasVendidos()
        {
            var reporte = context.Database.SqlQuery<ProductoVendido>(
                "EXEC sp_Reportes_ProductosMasVendidos"
            ).ToList();

            return View(reporte);
        }
    }
}

LabG9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>



</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Food Shop", "Catalogo", "Producto", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Catalogo", "Catalogo", "Producto", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Historial", "HistorialPedido", "Factura", new { area = "" }, new { @class = "nav-link" })</li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Gestion Productos", "GestionProductos", "Producto", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Facturas", "Facturas", "Factura", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Ventas Por Mes", "VentasPorMes", "Reportes", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Producto Mas Vendido", "ProductosMasVendidos", "Reportes", new { area = "" }, new { @class = "nav-link" })</li>
                    }


                </ul>


                @Html.Partial("_LoginPartial")
                <a class="nav-link text-white" href="@Url.Action("VerCarrito", "Carrito")">
                    <i class="bi bi-cart"></i>
                </a>

            </div>
        </div>

    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>